name: Supercreator Desktop TestDriver
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  test-action:
    name: Supercreator Desktop TestDriver
    runs-on: macos-latest
    steps:
      - uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: |
            1. /run testdriver/install_login_mac.yml
            2. /run testdriver/ui.yml
          os: mac
          prerun: |
            # Check if IPv6 is enabled
            if ifconfig | grep -q "inet6"; then
                echo "IPv6 is enabled"
            else
                echo "IPv6 is not enabled"
            fi

            # Ensure Dashcam is running
            if ! pgrep -x "Dashcam" > /dev/null; then
                echo "Error: Dashcam is not running!"
                exit 1
            fi

            # URL for the Supercreator installer
            installerUrl="https://storage.googleapis.com/app-versions/Supercreator-x64-latest.dmg"

            # Location to save the installer
            installerPath="$HOME/Desktop/SupercreatorInstaller.dmg"

            # Download the Supercreator installer
            echo "Downloading Supercreator installer..."
            curl -L "$installerUrl" -o "$installerPath"

            # Check if the download was successful
            if [ -f "$installerPath" ]; then
                echo "Download successful. Mounting the installer..."
                
                # Mount the DMG file
                hdiutil attach "$installerPath" -nobrowse -quiet
                
                # Find the mounted volume (assumes there's only one new volume)
                volumePath=$(ls /Volumes | grep -i "Supercreator" | head -n 1)

                if [ -n "$volumePath" ]; then
                    echo "Installer mounted at /Volumes/$volumePath"
                    
                    # Run the installer (if it's a .app, adapt if it's a .pkg)
                    open "/Volumes/$volumePath/Supercreator.app"
                    
                    # Wait before unmounting
                    sleep 10
                    
                    # Unmount the DMG
                    hdiutil detach "/Volumes/$volumePath" -quiet
                else
                    echo "Failed to find the mounted installer."
                fi
            else
                echo "Failed to download the Supercreator installer."
            fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"
