name: TestDriver.ai / SuperCreator

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *" 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:      
      - uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: | 
            1. /run testdriver/login.yml
            2. /run testdriver/ui.yml
          prerun: |
            Get-NetIPAddress -AddressFamily IPv6
            # URL for the SuperCreator installer
            $installerUrl = "https://storage.googleapis.com/app-versions/supercreator-setup-latest.exe"
            # Location to save the installer
            $installerPath = "$env:USERPROFILE\Downloads\SuperCreatorInstaller.exe"
            # Download the SuperCreator installer
            Write-Host "Downloading SuperCreator installer..."
            Invoke-WebRequest -Uri $installerUrl -OutFile $installerPath
            # Check if the download was successful
            if (Test-Path $installerPath) {
                Write-Host "Download successful. Running the installer..."
                Start-Process -FilePath $installerPath -ArgumentList '/silent' -Wait
                Start-Sleep -Seconds 10
            } else {
                Write-Host "Failed to download the SuperCreator installer."
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"
          TD_TEST_USERNAME: ${{ secrets.TD_TEST_USERNAME }}
          TD_TEST_PASSWORD: ${{ secrets.TD_TEST_PASSWORD }}
